name: image-build
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo.
        uses: actions/checkout@v2

      - name: Build and Push docker image.
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
          bash build.sh
